### ISSUE TITLE
Should SolR schema be added to repository

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#39]
Should we add the SolR schema to this repository? Then we can update that according to the MMD specification when needed. Any opinions?

**Comment by hevgyrt** [comment]
Sounds OK to me. In case we should have **one** Schema for L1, L2 and thumbnail, and not the schemas for all the cores?

**Comment by mortenwh** [comment]
What is the SolR schema?

**Comment by steingod** [comment]
The practical implementation of MMD elements in SolR (i.e. the search engine) used in the web based search interface supporting facets etc.

**Comment by ferrighi** [comment]
Good yes! It should be a reasonable place to have it.

**Comment by epifanio** [comment]
Quick notes on how to export/replicate/inspect a SOLR schema:

The schema for a SOLR core can be exported from a SOLR service using curl. 

e.g.: for the `nbs-l1 core`:

```
curl http://host:port/solr/core_name/schema?wt=json
```

The `JSON` produced can be inspected for:

- `fieldtypes`
- `fields`
- `dynamicfields`
- `copyfields`

I was using the `JSON` schema in a [notebook](https://gist.github.com/5d6394055a4028e6b3c2b76314b61b52) in order to replicate the NBS SOLR cores schemas on the docker SOLR image.

**Comment by steingod** [comment]
Schemas are downloaded and added to xsd folder.
