### ISSUE TITLE
Document build process and automate releases

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#4]
Releases has to be automated in local repositories.

**Comment by steingod** [comment]
Should copy the CF-conventions work flow using Travis.

**Comment by steingod** [comment]
@magnarem is this something you could look into? E.g. automatic build of the PDF here and potentially at ADC as well?

**Comment by mortenwh** [comment]
This could perhaps be done in S-ENDA as well. We need to handle CI for all the relevant repo's.

**Comment by mortenwh** [comment]
I'll add it as a potential task in the sprint

**Comment by steingod** [comment]
That would be good.

**Comment by mortenwh** [comment]
Would be good if this could be prioritized for the sprint. Both to have CI for MMD but also as an exercise in setting it up, since we don't have many repo's at the moment. Any opinions? @aheimsbakk @ferrighi @mpejcoch

**Comment by mortenwh** [comment]
I have looked into this now. Some issues:
- There is a serious security challenge with this approach, because we risk to reveal access tokens (I have deleted mine now, as it would be quite easy to get it)
- I feel that using Travis CI for this purpose is wrong, as this tool is mainly for testing
- Binaries should not be version controlled, they fill up the history and should rather be built outside the repo
- We still need to have (unit) tests for this repo, so integration with Travis CI in that respect makes perfect sense

I suggest the following:
- Create a new issue for unit testing (I can take on that task)
- Integrate with, e.g., readthedocs - they have automatic builds on every commit, including html and pdf (this may, however, require translation from adoc to rst format)

**Comment by mortenwh** [comment]
Issue for unit testing and coverage, see: https://github.com/steingod/mmd/issues/74

**Comment by aheimsbakk** [comment]
Added suggestion for automatic build of HTML and PDF in pull request #80. I have an idea for integrating coverage testing with GitHub actions with https://github.com/coverallsapp/github-action/.

**Comment by mortenwh** [comment]
Building pdf and html documentation is now handled in GH-80 (https://github.com/steingod/mmd/pull/80). With that, I consider that this task is done. CI for automatic testing and coverage reporting is handled in #74.
